// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STK.Persistance;

#nullable disable

namespace STK.Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250123193141_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EconomicActivityOrganization", b =>
                {
                    b.Property<Guid>("EconomicActivitiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("EconomicActivitiesId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationEconomicActivity", (string)null);
                });

            modelBuilder.Entity("STK.Domain.Entities.BalanceSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .HasColumnType("text");

                    b.Property<decimal?>("CapitalReserves")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CurrentActive")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LongTermLiabilities")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NonCurrentActive")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ShortTermLiabilities")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BalanceSheets");
                });

            modelBuilder.Entity("STK.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificationObject")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfCertificateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfIssueCertificate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeclarationOfConformity")
                        .HasColumnType("text");

                    b.Property<string>("NameOrganization")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Tittle")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("STK.Domain.Entities.EconomicActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discription")
                        .HasColumnType("text");

                    b.Property<string>("OKVDNnumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EconomicActivities");
                });

            modelBuilder.Entity("STK.Domain.Entities.FinancialResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostOfSales")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GrossProfitEarnings")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GrossProfitRevenue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ProfitBeforeTax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalesProfit")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("FinancialResults");
                });

            modelBuilder.Entity("STK.Domain.Entities.Management", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Managements");
                });

            modelBuilder.Entity("STK.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adress")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("IndexAdress")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParrentOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("STK.Domain.Entities.Requisite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthorizedCapital")
                        .HasColumnType("integer");

                    b.Property<int?>("AvgCountEmployee")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstablishmentCreateName")
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .HasColumnType("text");

                    b.Property<string>("KPP")
                        .HasColumnType("text");

                    b.Property<string>("OGRN")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Proceeds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("Requisites");
                });

            modelBuilder.Entity("EconomicActivityOrganization", b =>
                {
                    b.HasOne("STK.Domain.Entities.EconomicActivity", null)
                        .WithMany()
                        .HasForeignKey("EconomicActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STK.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("STK.Domain.Entities.BalanceSheet", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithMany("BalanceSheets")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithMany("Certificates")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.FinancialResult", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithMany("FinancialResults")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.Management", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithMany("Managements")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.Requisite", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithOne("Requisites")
                        .HasForeignKey("STK.Domain.Entities.Requisite", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.Organization", b =>
                {
                    b.Navigation("BalanceSheets");

                    b.Navigation("Certificates");

                    b.Navigation("FinancialResults");

                    b.Navigation("Managements");

                    b.Navigation("Requisites");
                });
#pragma warning restore 612, 618
        }
    }
}
