// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STK.Persistance;

#nullable disable

namespace STK.Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

 
            modelBuilder.Entity("OrganizationTaxMode", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaxesModesId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "TaxesModesId");

                    b.HasIndex("TaxesModesId");

                    b.ToTable("OrganizationTaxMode", (string)null);
                });

            modelBuilder.Entity("STK.Domain.Entities.BalanceSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .HasColumnType("text");

                    b.Property<decimal?>("CapitalReserves")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CurrentActive")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LongTermLiabilities")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NonCurrentActive")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ShortTermLiabilities")
                        .HasColumnType("numeric");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BalanceSheets");
                });

            modelBuilder.Entity("STK.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Applicant")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CertificateRenewalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CertificateSuspensionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CertificationObject")
                        .HasColumnType("text");

                    b.Property<string>("CertificationType")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfCertificateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfIssueCertificate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("ManufacturerAddress")
                        .HasColumnType("text");

                    b.Property<string>("ManufacturerCity")
                        .HasColumnType("text");

                    b.Property<string>("ManufacturerCountry")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrescriptionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("SuspensionHistory")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("STK.Domain.Entities.EconomicActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("OKVDNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EconomicActivities");
                });

            modelBuilder.Entity("STK.Domain.Entities.FinancialResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostOfSales")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GrossProfitEarnings")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GrossProfitRevenue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IncomeTaxe")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ProfitBeforeTax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalesProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TaxFee")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("FinancialResults");
                });

            modelBuilder.Entity("STK.Domain.Entities.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameOrganizationIssued")
                        .HasColumnType("text");

                    b.Property<string>("NameTypeActivity")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeriesNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("STK.Domain.Entities.Management", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Managements");
                });

            modelBuilder.Entity("STK.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("IndexAddress")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("StatusOrg")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("STK.Domain.Entities.OrganizationEconomicActivity", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EconomicActivityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.HasKey("OrganizationId", "EconomicActivityId");

                    b.HasIndex("EconomicActivityId");

                    b.ToTable("OrganizationsEconomicActivities");
                });

            modelBuilder.Entity("STK.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("STK.Domain.Entities.Requisite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AuthorizedCapital")
                        .HasColumnType("integer");

                    b.Property<int?>("AvgCountEmployee")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstablishmentCreateName")
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .HasColumnType("text");

                    b.Property<string>("KPP")
                        .HasColumnType("text");

                    b.Property<string>("OGRN")
                        .HasColumnType("text");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypeOfCapital")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("Requisites");
                });

            modelBuilder.Entity("STK.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("STK.Domain.Entities.TaxMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaxesModes");
                });

            modelBuilder.Entity("STK.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("STK.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("EconomicActivityOrganization", b =>
                {
                    b.HasOne("STK.Domain.Entities.EconomicActivity", null)
                        .WithMany()
                        .HasForeignKey("EconomicActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STK.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrganizationTaxMode", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STK.Domain.Entities.TaxMode", null)
                        .WithMany()
                        .HasForeignKey("TaxesModesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("STK.Domain.Entities.BalanceSheet", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithMany("BalanceSheets")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithMany("Certificates")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.FinancialResult", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithMany("FinancialResults")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.License", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithMany("Licenses")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.Management", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithMany("Managements")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.OrganizationEconomicActivity", b =>
                {
                    b.HasOne("STK.Domain.Entities.EconomicActivity", "EconomicActivities")
                        .WithMany("OrganizationsEconomicActivities")
                        .HasForeignKey("EconomicActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STK.Domain.Entities.Organization", "Organizations")
                        .WithMany("OrganizationsEconomicActivities")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EconomicActivities");

                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("STK.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("STK.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("STK.Domain.Entities.Requisite", b =>
                {
                    b.HasOne("STK.Domain.Entities.Organization", "Organization")
                        .WithOne("Requisites")
                        .HasForeignKey("STK.Domain.Entities.Requisite", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("STK.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("STK.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STK.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STK.Domain.Entities.EconomicActivity", b =>
                {
                    b.Navigation("OrganizationsEconomicActivities");
                });

            modelBuilder.Entity("STK.Domain.Entities.Organization", b =>
                {
                    b.Navigation("BalanceSheets");

                    b.Navigation("Certificates");

                    b.Navigation("FinancialResults");

                    b.Navigation("Licenses");

                    b.Navigation("Managements");

                    b.Navigation("OrganizationsEconomicActivities");

                    b.Navigation("Requisites");
                });

            modelBuilder.Entity("STK.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("STK.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
